global:
  scrape_interval: 10s # 10초마다 타겟 서버의 상태(메트릭)를 수집합니다.

scrape_configs:
  # 1. 프로메테우스 자기 자신 상태 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. 로컬에서 실행 중인 Python agent 메트릭 수집
  - job_name: 'agent'
    static_configs:
      - targets: ['host.docker.internal:8000'] # Docker 내부에서 호스트 PC의 8000 포트 접근