server {
    listen 80;
    server_name _;

    # 기본 응답
    location / {
        return 200 'nginx target server OK\n';
        add_header Content-Type text/plain;
    }

    # 헬스체크 (Prometheus rule-based 탐지 대상)
    location /health {
        access_log off;
        return 200 'OK\n';
        add_header Content-Type text/plain;
    }
}
