"""Init AIOps tables

Revision ID: 29cd461fc97c
Revises: 
Create Date: 2026-03-25 14:10:24.796777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29cd461fc97c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('incident_types', postgresql.ARRAY(sa.Enum('CONTAINER_CRASH', 'OOM', 'DISK_FULL', 'HIGH_CPU', 'DB_CONNECTION', 'NGINX_5XX', name='incidenttypeenum')), nullable=False),
    sa.Column('trigger_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_node', sa.String(length=100), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DETECTED', 'ANALYZING', 'PENDING', 'RECOVERING', 'RESOLVED', 'FAILED', name='statusenum'), nullable=False),
    sa.Column('ai_title', sa.String(length=200), nullable=True),
    sa.Column('ai_severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severityenum'), nullable=True),
    sa.Column('llm_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incidents_detected_at', 'incidents', [sa.literal_column('detected_at DESC')], unique=False)
    op.create_index('idx_incidents_types', 'incidents', ['incident_types'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_incidents_ai_severity'), 'incidents', ['ai_severity'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_parent_id'), 'incidents', ['parent_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_target_node'), 'incidents', ['target_node'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('target_node', sa.String(length=100), nullable=False),
    sa.Column('metric_type', sa.Enum('DISK', 'MEMORY', 'CPU', name='metrictypeenum'), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_breach', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_expected_breach'), 'predictions', ['expected_breach'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_incident_id'), 'predictions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_predictions_target_node'), 'predictions', ['target_node'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('RESTART_CONTAINER', 'CLEAR_LOGS', 'DOCKER_PRUNE', 'RESTART_PROCESS', 'SCALE_OUT', name='actiontypeenum'), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatusenum'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=True),
    sa.Column('log_snippet', sa.Text(), nullable=True),
    sa.CheckConstraint('incident_id IS NOT NULL OR prediction_id IS NOT NULL', name='check_action_target'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_actions_id'), 'recovery_actions', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_incident_id'), 'recovery_actions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_prediction_id'), 'recovery_actions', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_recovery_actions_prediction_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_incident_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_id'), table_name='recovery_actions')
    op.drop_table('recovery_actions')

    op.drop_index(op.f('ix_predictions_target_node'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_incident_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_expected_breach'), table_name='predictions')
    op.drop_table('predictions')

    op.drop_index(op.f('ix_incidents_target_node'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_parent_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_ai_severity'), table_name='incidents')

    op.drop_index('idx_incidents_types', table_name='incidents') 
    op.drop_index('idx_incidents_detected_at', table_name='incidents')
    op.drop_table('incidents')

    op.execute("DROP TYPE IF EXISTS incidenttypeenum")
    op.execute("DROP TYPE IF EXISTS statusenum")
    op.execute("DROP TYPE IF EXISTS severityenum")
    op.execute("DROP TYPE IF EXISTS metrictypeenum")
    op.execute("DROP TYPE IF EXISTS actiontypeenum")
    op.execute("DROP TYPE IF EXISTS approvalstatusenum")
    # ### end Alembic commands ###
