"""add_params_to_recovery_actions

Revision ID: b093a147e92c
Revises: 8d10c3a4a72d
Create Date: 2026-04-27 15:15:27.383064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b093a147e92c"
down_revision: Union[str, Sequence[str], None] = "8d10c3a4a72d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recovery_actions",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recovery_actions", "params")
    # ### end Alembic commands ###
